### ISSUE TITLE
请问代码从哪里开始运行呢？

### ISSUE THREAD

**Issue by liupenggg** [Weikoi/Resume_Recommender#1]
请问代码从哪里开始运行呢？

**Comment by Weikoi** [comment]
> 
> 
> 请问代码从哪里开始运行呢？

这是基于django的，直接用django命令行来启动，配完依赖以后，执行python manage.py runserver

**Comment by Rocky-crl** [comment]
> > 请问代码从哪里开始运行呢？
> 
> 这是基于django的，直接用django命令行来启动，配完依赖以后，执行python manage.py runserver

您好，方便加一下您的联系方式吗？我想向您更清晰的了解一些关于项目的内容

**Comment by Rocky-crl** [comment]
> 请问代码从哪里开始运行呢？

请问您是否跑通这个项目呢？
